# Generated by Django 2.2.7 on 2019-11-30 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tvshowapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshowapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', tvshowapp.models.TVShowUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(default='test', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
